# Architecture
arch: Net

# ===== Dataset ===== #
data: /mnt
set: MNIST
name: Net_usc_unsigned

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 9
weight_decay: 0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: FixFanInSubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1
init: signed_constant
# scale_fan: True

# ===== Hardware setup ===== #
workers: 2
