# Architecture
arch: ResNet50

# ===== Dataset ===== #
data: /mnt
set: ImageNet
name: imagenet_lr400

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 400
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0 #0.0001
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: SampleSubnetConv 
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1
init: kaiming_normal
# scale_fan: True

# ===== Hardware setup ===== #
workers: 20